### ISSUE TITLE
deploy가 안됩니다

### ISSUE THREAD

**Issue by thegreatkingbear** [raccoonyy/docker-compose-ghost-buster#1]
generate, preview까지는 무사히 진행되었고, deploy를 하면 다음과 같은 에러가 납니다.

Mookyungs-MacBook-Pro:blog mookyungkwak$ docker-compose exec buster ./deploy.sh
Traceback (most recent call last):
  File "/usr/local/bin/buster", line 11, in <module>
    load_entry_point('buster==0.1.3', 'console_scripts', 'buster')()
  File "/usr/local/lib/python2.7/site-packages/buster/buster.py", line 197, in main
    repo = Repo(static_path)
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 156, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /deploy/static

그래서 docker의 Kitematic으로 blog_buster_1 container의 logs를 보면 다음과 같습니다.

LOGNAME: MY_USER_NAME
EMAILL: MY@EMAIL_ADDRESS
Cloning into 'static'...
Host key verification failed.
fatal: Could not read from remote repository.
2017-02-03T19:29:50.118048183Z 
Please make sure you have the correct access rights
and the repository exists.
./run.sh: line 11: cd: /deploy/static: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git

.env 는 다음과 같이 구성했습니다.

  1 GITHUB_ID=깃헙유저아이디                                                                                          
  2 LOGNAME=깃헙유저아이디                                                                                            
  3 EMAIL=깃헙로그인이메일                                                                                           
  4 NODE_ENV=production                                                                                                 
  5 SSH_KEY=~/.ssh/id_rsa 

ssh_key도 발급받아서 깃헙에 넣어줬구요. 뭘 해야 할까요? 초보라 잘 모르겠습니다 ㅠ

**Comment by raccoonyy** [comment]
깃헙에 `깃헙아이디.github.io` 저장소를 만드셨나요?

**Comment by thegreatkingbear** [comment]
네 물론입니다 :)

**Comment by raccoonyy** [comment]
`Host key verification failed.` 오류를 찾아보니,
1. ssh 키가 틀린 경우
2. ssh 접속 정보가 `known_hosts` 파일에 들어 있지 않은 경우

가 가장 많은데요.

1번은 아닌 듯 하고, 2번이라고 짐작해봅니다.

로컬 컴퓨터에서 다음 명령을 실행하신 후 재시도해보시겠어요?
```
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
```

**Comment by thegreatkingbear** [comment]
위의 명령을 실행해도 안되어서, 

docker-compose exec buster bash 으로 들어가서 
setup을 다시 실행시켜서 깃헙의 해당 저장소 주소를 입력해주고
exit로 나온 다음에 
generate와 deploy를 해주고
deploy에서 유저네임과 비밀번호를 입력해주니까 되네요~

제가 .env를 잘못 입력한걸까요?

**Comment by raccoonyy** [comment]
Github에 리포를 생성해도, 커밋이 하나도 없으면 clone을 받지 못하여 발생하는 문제였습니다.
리포를 만들 때 README.md를 기본으로 추가하게 해두면 해결되네요. :)
해당 이슈는 README에 업데이트해두겠습니다.

문제를 알려주셔서 고맙습니다. ^^

**Comment by thegreatkingbear** [comment]
적극적으로 대응해주셔서 감사합니다~
근데 역시 setup을 안 하면 마찬가지로 에러가 나는데요. (일단 성공한 뒤라도 매번 generate해주기 전에 setup을 해줘야 합니다)
뭐가 문제일까요?

**Comment by raccoonyy** [comment]
제가 재현한 문제가 아닌 다른 문제인가 보네요.
살펴보겠습니다.

혹시 오류 코드는 위와 동일한가요?

꾸준히 문제를 알려주셔서 고맙습니다. :)

**Comment by thegreatkingbear** [comment]
네 그냥 generate만 한 다음에 deploy를 하면 다음과 같은 에러가 납니다

Mookyungs-MacBook-Pro:blog mookyungkwak$ docker-compose exec buster ./deploy.sh
Traceback (most recent call last):
  File "/usr/local/bin/buster", line 11, in <module>
    load_entry_point('buster==0.1.3', 'console_scripts', 'buster')()
  File "/usr/local/lib/python2.7/site-packages/buster/buster.py", line 197, in main
    repo = Repo(static_path)
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 156, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /deploy/static

당장 저부터 무척 유용하게 쓸 수 있을것 같아서요~ 👍
